### PR TITLE
Add a systemd unit for arch and a wireshark dissector

### PR DESCRIPTION
**Pull request by nbrownus**
- First cut at a unified wireshark dissector
- Systemd unit for arch in repo

### CODE REVIEW

**Comment by virtadpt** [comment]
It might be worth moving that .service file out of the Arch-specific directory.  It looks a lot like the one I use on Raspbian, Ubuntu, and Arch.

**Comment by TheTyrius** [comment]
Sorry if this is obvious, but why are there two (seemingly) very similar service files in the source tree (under examples and now dist)?

**Comment by nbrownus** [comment]
The one in examples uses a path to the binary that most distros won't be
using. This lead to an issue with arch specifically where the package did
not contain a unit file. Instead of breaking anyone relying on the one in
examples we chose to publish a new one in a very specific place to allow
arch to move forward.

**Comment by willemw12** [comment]
I agree with @virtadpt: there is nothing distro-specific with that "Arch" systemd unit file (for creating an installable package). Except maybe syslog?

**Pull request merged**
