### PR TITLE
Use CGO_ENABLED=0

### PR DESCRIPTION
**Pull request by RealOrangeOne**
Fixes https://github.com/slackhq/nebula/issues/295

_Might_ fix https://github.com/slackhq/nebula/issues/338

Also impacts https://github.com/slackhq/nebula/pull/48 and https://github.com/slackhq/nebula/pull/68/

Naive attempt to create statically linked binaries, suitable for dstros like Alpine. Unlike previously, binaries now execute on Alpine.

Binary still appears to execute and connect to tunnels fine on Arch.

```
$ file nebula
nebula: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=-XXX, not stripped
```

### CODE REVIEW

**Comment by wadey** [comment]
I agree with this change, but only for `linux` builds. I think cgo does some things on darwin, windows that might be necessary there. The only thing that CGO does for us on linux is hostname lookups, but I don't think that should be an issue for most people. The power of having repeatable builds by disabling CGO would be very nice.

Do you think you could change this to only disable CGO on linux builds?

**Comment by RealOrangeOne** [comment]
A quick google search yields no really useful references other than "Where Go calls C". [This](https://stackoverflow.com/questions/61515186/when-using-cgo-enabled-is-must-and-what-happens) is a bit of an interesting read.

I don't have access to a windows or macOS machine to try this patch out, but perhaps instead we should test this on windows and macos to see if it's better / no worse? Using the same compiler flags for each OS is probably a good thing, especially if that 1 OS is the one most of CI runs against.

Alternatively, perhaps instead specifically using `netgo` is an option (`go build -tags osusergo,netgo`). I'll give that a try this evening to see if that also solves the issue without completely disabling CGo.

**Comment by RealOrangeOne** [comment]
@wadey I found a simpler way. By explicitly using `netgo` explicitly instead of the cgo implementation, we keep the benefits of using `cgo` for some things, but with the cross-platform benefits.

I _think_ I prefer this approach?

**Comment by RealOrangeOne** [comment]
I know little about Go's internals, but yeah I do kinda prefer the cgo approach, that's also how [Hugo](https://github.com/gohugoio/hugo/blob/master/goreleaser.yml#L14) does it.

I'll leave the branch as-is for now. Think and I can revert if needed.

I'm really keen to get this merged and shipped ASAP, as it'll help out a lot of platforms!

**Comment by wadey** [comment]
I've updated this PR to just set CGO_ENABLED=0, which I think is the better option. I have been testing with this and see no issues.

**Review by nbrownus — APPROVED** [review]

**Pull request merged**
