### PR TITLE
Add nss-lookup to the systemd wants

### LINKED ISSUE #745: 🐛 BUG: Nebula crash on "Static host address could not be parsed"
### What version of `nebula` are you using?

1.6.0

### What operating system are you using?

Linux

### Describe the Bug

I use FQDN for lighthouse addresses.
When Nebula starts, if the network is not yet fully up, the DNS resolution fails and Nebula crashes.
My expectation would be that Nebula does _not_ crash and retries over time in the same way it does when it can resolve the FQDN to an IP but Nebula is not able to establish a connection.

### Logs from affected hosts

```
-- Boot 6ba68dc9aa554b0094f3a442acb37401 --
Sep 05 09:22:42 x1.fale.io nebula[1259]: time="2022-09-05T09:22:42+02:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
Sep 05 09:22:42 x1.fale.io nebula[1259]: time="2022-09-05T09:22:42+02:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:1 startPort:0]"
Sep 05 09:22:42 x1.fale.io nebula[1259]: time="2022-09-05T09:22:42+02:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:22 groups:[fale ssh] host: ip: proto:6 startPort:22]"
Sep 05 09:22:42 x1.fale.io nebula[1259]: time="2022-09-05T09:22:42+02:00" level=info msg="Firewall started" firewallHash=e9fc6276b1f92e11afb6da6c768e57eae28a9aaab95b14daadb95cbce6f432af
Sep 05 09:22:42 x1.fale.io nebula[1259]: time="2022-09-05T09:22:42+02:00" level=info msg="Main HostMap created" network=192.168.100.32/24 preferredRanges="[]"
Sep 05 09:22:42 x1.fale.io nebula[1259]: time="2022-09-05T09:22:42+02:00" level=info msg="UDP hole punching enabled"
Sep 05 09:22:42 x1.fale.io nebula[1259]: time="2022-09-05T09:22:42+02:00" level=error msg="Static host address could not be parsed" error="lookup lh4.fale.io: Temporary failure in name resolution" vpnIp=192.168.100.4
```

### Config files from affected hosts

```
...
static_host_map:
  192.168.100.1:
    - lh1.fale.io:4242
  192.168.100.2:
    - lh2.fale.io:4242
  192.168.100.3:
    - lh3.fale.io:4242
  192.168.100.4:
    - lh4.fale.io:4242

lighthouse:
  hosts:
    - 192.168.100.1
    - 192.168.100.2
    - 192.168.100.3
    - 192.168.100.4
...
```

### LINKED ISSUE #797: 🐛 BUG: Nebula systemd unit fails to start if the clock is too off
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

Linux

### Describe the Bug

When starting `nebula` with systemd unit, on systems that do not have a clock battery (eg: RPis), if the clock will automatically reset to a moment in time that is prior to the creation of the CA, nebula will fail directly.

This can be fixed by enabling `systemd-time-wait-sync` and wanting for `time-sync.target`.

### Logs from affected hosts

Note: the logs have been collected on 2022-12-16, even though they have a time that is in July due to the fact that the NTP-based clock-sync daemon did not started yet.

```
Jul 14 00:00:22 rpi0.fale.io systemd[1]: Started nebula.service - nebula.
Jul 14 00:00:23 rpi0.fale.io nebula[809]: time="2022-07-14T00:00:23Z" level=warning msg="expired certificate present in CA pool" cert="NebulaCertificate {\n\tDetails {\n\t\tName: FalePrivateNet\n\t\tIps: []\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2022-09-03 07:54:33 +0000 UTC\n\t\tNot After: 2032-08-31 07:54:33 +0000 UTC\n\t\tIs CA: true\n\t\tIssuer: \n\t\tPublic key: 91c5a8c9aecb98a9152b0171f5f3a8d7dcf4f433a0605dd32aaabc27570a1704\n\t}\n\tFingerprint: 8bfad74452a0073bd716c1d6f5da8de281785857e1ed3a0f02f4de441bcd36b5\n\tSignature: 2c5acfcde6fd42f0dee74fc72a06da0d636c6c0fc40b4034036589f82840d16a2db3c0855f8fd4e664abd233cdc5608690a9a96939c74d1e36901ae431dac90f\n}"
Jul 14 00:00:23 rpi0.fale.io nebula[809]: time="2022-07-14T00:00:23Z" level=error msg="Failed to load ca from config" error="no valid CA certificates present"
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Failed with result 'exit-code'.
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Scheduled restart job, restart counter is at 1.
Jul 14 00:00:23 rpi0.fale.io systemd[1]: Stopped nebula.service - nebula.
Jul 14 00:00:23 rpi0.fale.io systemd[1]: Started nebula.service - nebula.
Jul 14 00:00:23 rpi0.fale.io nebula[859]: time="2022-07-14T00:00:23Z" level=warning msg="expired certificate present in CA pool" cert="NebulaCertificate {\n\tDetails {\n\t\tName: FalePrivateNet\n\t\tIps: []\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2022-09-03 07:54:33 +0000 UTC\n\t\tNot After: 2032-08-31 07:54:33 +0000 UTC\n\t\tIs CA: true\n\t\tIssuer: \n\t\tPublic key: 91c5a8c9aecb98a9152b0171f5f3a8d7dcf4f433a0605dd32aaabc27570a1704\n\t}\n\tFingerprint: 8bfad74452a0073bd716c1d6f5da8de281785857e1ed3a0f02f4de441bcd36b5\n\tSignature: 2c5acfcde6fd42f0dee74fc72a06da0d636c6c0fc40b4034036589f82840d16a2db3c0855f8fd4e664abd233cdc5608690a9a96939c74d1e36901ae431dac90f\n}"
Jul 14 00:00:23 rpi0.fale.io nebula[859]: time="2022-07-14T00:00:23Z" level=error msg="Failed to load ca from config" error="no valid CA certificates present"
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Failed with result 'exit-code'.
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Scheduled restart job, restart counter is at 2.
Jul 14 00:00:23 rpi0.fale.io systemd[1]: Stopped nebula.service - nebula.
Jul 14 00:00:23 rpi0.fale.io systemd[1]: Started nebula.service - nebula.
Jul 14 00:00:23 rpi0.fale.io nebula[886]: time="2022-07-14T00:00:23Z" level=warning msg="expired certificate present in CA pool" cert="NebulaCertificate {\n\tDetails {\n\t\tName: FalePrivateNet\n\t\tIps: []\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2022-09-03 07:54:33 +0000 UTC\n\t\tNot After: 2032-08-31 07:54:33 +0000 UTC\n\t\tIs CA: true\n\t\tIssuer: \n\t\tPublic key: 91c5a8c9aecb98a9152b0171f5f3a8d7dcf4f433a0605dd32aaabc27570a1704\n\t}\n\tFingerprint: 8bfad74452a0073bd716c1d6f5da8de281785857e1ed3a0f02f4de441bcd36b5\n\tSignature: 2c5acfcde6fd42f0dee74fc72a06da0d636c6c0fc40b4034036589f82840d16a2db3c0855f8fd4e664abd233cdc5608690a9a96939c74d1e36901ae431dac90f\n}"
Jul 14 00:00:23 rpi0.fale.io nebula[886]: time="2022-07-14T00:00:23Z" level=error msg="Failed to load ca from config" error="no valid CA certificates present"
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Failed with result 'exit-code'.
Jul 14 00:00:23 rpi0.fale.io systemd[1]: nebula.service: Scheduled restart job, restart counter is at 3.
Jul 14 00:00:23 rpi0.fale.io systemd[1]: Stopped nebula.service - nebula.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: Started nebula.service - nebula.
Jul 14 00:00:24 rpi0.fale.io nebula[904]: time="2022-07-14T00:00:24Z" level=warning msg="expired certificate present in CA pool" cert="NebulaCertificate {\n\tDetails {\n\t\tName: FalePrivateNet\n\t\tIps: []\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2022-09-03 07:54:33 +0000 UTC\n\t\tNot After: 2032-08-31 07:54:33 +0000 UTC\n\t\tIs CA: true\n\t\tIssuer: \n\t\tPublic key: 91c5a8c9aecb98a9152b0171f5f3a8d7dcf4f433a0605dd32aaabc27570a1704\n\t}\n\tFingerprint: 8bfad74452a0073bd716c1d6f5da8de281785857e1ed3a0f02f4de441bcd36b5\n\tSignature: 2c5acfcde6fd42f0dee74fc72a06da0d636c6c0fc40b4034036589f82840d16a2db3c0855f8fd4e664abd233cdc5608690a9a96939c74d1e36901ae431dac90f\n}"
Jul 14 00:00:24 rpi0.fale.io nebula[904]: time="2022-07-14T00:00:24Z" level=error msg="Failed to load ca from config" error="no valid CA certificates present"
Jul 14 00:00:24 rpi0.fale.io systemd[1]: nebula.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 00:00:24 rpi0.fale.io systemd[1]: nebula.service: Failed with result 'exit-code'.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: nebula.service: Scheduled restart job, restart counter is at 4.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: Stopped nebula.service - nebula.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: Started nebula.service - nebula.
Jul 14 00:00:24 rpi0.fale.io nebula[911]: time="2022-07-14T00:00:24Z" level=warning msg="expired certificate present in CA pool" cert="NebulaCertificate {\n\tDetails {\n\t\tName: FalePrivateNet\n\t\tIps: []\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2022-09-03 07:54:33 +0000 UTC\n\t\tNot After: 2032-08-31 07:54:33 +0000 UTC\n\t\tIs CA: true\n\t\tIssuer: \n\t\tPublic key: 91c5a8c9aecb98a9152b0171f5f3a8d7dcf4f433a0605dd32aaabc27570a1704\n\t}\n\tFingerprint: 8bfad74452a0073bd716c1d6f5da8de281785857e1ed3a0f02f4de441bcd36b5\n\tSignature: 2c5acfcde6fd42f0dee74fc72a06da0d636c6c0fc40b4034036589f82840d16a2db3c0855f8fd4e664abd233cdc5608690a9a96939c74d1e36901ae431dac90f\n}"
Jul 14 00:00:24 rpi0.fale.io nebula[911]: time="2022-07-14T00:00:24Z" level=error msg="Failed to load ca from config" error="no valid CA certificates present"
Jul 14 00:00:24 rpi0.fale.io systemd[1]: nebula.service: Main process exited, code=exited, status=1/FAILURE
Jul 14 00:00:24 rpi0.fale.io systemd[1]: nebula.service: Failed with result 'exit-code'.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: nebula.service: Scheduled restart job, restart counter is at 5.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: Stopped nebula.service - nebula.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: nebula.service: Start request repeated too quickly.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: nebula.service: Failed with result 'exit-code'.
Jul 14 00:00:24 rpi0.fale.io systemd[1]: Failed to start nebula.service - nebula.
```

### Config files from affected hosts

```
pki:
  ca: |
    -----BEGIN NEBULA CERTIFICATE-----
    CkAKDkZhbGVQcml2YXRlTmV0KLmQzJgGMLmW/K4HOiCRxajJrsuYqRUrAXH186jX
    3PT0M6BgXdMqqrwnVwoXBEABEkAsWs/N5v1C8N7nT8cqBtoNY2xsD8QLQDQDZYn4
    KEDRai2zwIVfj9TmZKvSM83FYIaQqalpOcdNHjaQGuQx2skP
    -----END NEBULA CERTIFICATE-----
  cert:  [omitted]
  key:  [omitted]

static_host_map:
  192.168.100.1:
    - lh1.fale.io:4242
  192.168.100.2:
    - lh2.fale.io:4242
  192.168.100.3:
    - lh3.fale.io:4242
  192.168.100.4:
    - lh4.fale.io:4242

lighthouse:
  am_lighthouse: true

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true
  respond: true

tun:
  dev: nebula1

relay:
  am_relay: true

firewall:
  outbound:
    - port: any
      proto: any
      host: any
```

### PR DESCRIPTION
**Pull request by Fale**
Ensure DNS is running before starting nebula.
Fixes #745. Thanks a lot @JohnMaguire for the suggestion :-)
Closes #792 
Fixes #797

### CODE REVIEW

**Comment by Fale** [comment]
I've added the fix for #797, merged #792 changes and aligned the files, if not the `Before=sshd.service` in Arch, even if from what I've seen in the last few days it to should be safe to do so that we have all the service files aligned :-)

**Review by wadey — APPROVED** [review]
I don't see any issues with this, and it should help a lot with problems folks have :+1:

**Comment by JohnMaguire** [comment]
This PR also fixes #176 and #372.

**Comment by JohnMaguire** [comment]
Thanks for the work on this @Fale!

**Pull request merged**
