### PR TITLE
Add 'tun.su' option to allow changing users after configuring the tunnel

### PR DESCRIPTION
**Pull request by numinit**
Other VPNs (e.g. Tinc) let you drop privileges from root after the tunnel is created.

Add a `tun.su` option specifying which user to drop privileges to. That way, Nebula can be started as root and run as a lesser privileged user.

Tested on Linux. Still have to test FreeBSD and Darwin. The `tun.su` option gets ignored on other platforms.

### CODE REVIEW

**Comment by gearnode** [comment]
Any update on this contribution? (cc @nbrownus @numinit)

**Comment by numinit** [comment]
I feel like the need to sign a CLA to merge deters me from contributing to this project, and "Like many open source projects" is a red herring.

That being said, I am fully willing to license this patch under the MIT license, which Nebula is licensed under anyway.

**Comment by numinit** [comment]
To be very clear - I made this PR because I'm running this patch on several systems, [and have a writeup about it](https://numinit.tumblr.com/post/671446357227274240/creating-a-distributed-private-cloud-with-nebula), and it's really useful for me, and I thought it would be worth it to share.

I just feel like the CLA has a chilling effect on people's ability to contribute to Nebula, which is a shame for contributions that are genuinely useful to people. That being said, I hope people get use out of it in their own patches to Nebula, since it's open source and MIT licensed anyway. 😃

**Comment by numinit** [comment]
Closing as this is fixable with systemd-exec.

https://github.com/NixOS/nixpkgs/pull/208189

**Pull request closed without merging**
