### PR TITLE
Add Wintun support

### PR DESCRIPTION
**Pull request by CzBiX**
Users required to install wireguard to get wintun driver.

### CODE REVIEW

**Comment by CzBiX** [comment]
Fix #116

**Comment by wadey** [comment]
This is awesome, thank you so much!

To merge this, I think we need to make sure this won't break any existing users of Nebula that are using the OpenVPN tun driver. Could you update your patch to retain support for the old driver, but select the wintun driver if it is installed? I'm thinking perhaps we have `tun_water_windows.go` and `tun_wintun_windows.go` and we have a small stub in `tun_windows.go` to select which one to use based on the installed driver. If you have a better idea for how to go about this, feel free to try another route too. I just want to make sure we don't leave any existing users scratching their heads when they upgrade (at least have a deprecation period for folks to switch over).

In the future after this PR has been merged I'd like to set up a build process to create a `.msi` that includes the wintun driver as well, which will also hopefully solve this for new users.

Thanks again, let us know if you aren't interested in making those changes as well and we can take the reigns.

**Comment by CzBiX** [comment]
@wadey Done, please review.

**Comment by CzBiX** [comment]
I don't know why, Microsoft Security will reported virus.
I tinkered a bit, it won't complain now.

**Comment by wadey** [comment]
Thanks for updating your PR, I just want to do a little more testing with this before we merge :+1:

**Comment by wadey** [comment]
I was working on finishing up some testing for this, but they just announced today the release of Wintun 0.9 which is supposed to make distribution of the driver much easier. So I guess we should look at what it will take to upgrade to 0.9

https://lists.zx2c4.com/pipermail/wireguard/2020-November/005921.html

**Comment by CzBiX** [comment]
The new version wintun is much easier to integrated.
But I found that wintun is licensed at GPL, which is incompatible with MIT.
Just send an email about license change to wireguard mail list.

**Comment by ofer-dev** [comment]
I think https://github.com/WireGuard/wintun/commit/6af568d1e0edaa6809d99e7be5e13825c5e8bee6 solves license compatibility issues. wintun.h is now duel licensed under GPL and MIT.

**Comment by CzBiX** [comment]
> I think [WireGuard/wintun@6af568d](https://github.com/WireGuard/wintun/commit/6af568d1e0edaa6809d99e7be5e13825c5e8bee6) solves license compatibility issues. wintun.h is now licensed under GPL and MIT.

Sorry, but it doesn't. The usage of wintun required linking to wintun library, which will make our code be GPL too.
In fact, I found that the TAP windows driver also be GPLv2 licensed. 

BTW, I haven't received any response from the author of wintun/wireguard yet.
It seems that this pr can be closed now.

**Comment by wadey** [comment]
Did you send your email to Jason directly or to the mailing list? I was trying to find it on the mailing list and I didn't see it. Perhaps we are okay as long that file is MIT, but I need to brush up on GPL and DLLs.

Could you attach your previous email exchange about updating the header file license to this issue?

**Comment by CzBiX** [comment]
I send the email to mailing list. and received "Your message to WireGuard awaits moderator approval". that's all.

**Comment by ofer-dev** [comment]
Hey, the signed binary wintun.dll from https://www.wintun.net is under a different license then gpl. It is not an open source license but it allows to redistribute and link to wintun.dll as long as it is used only with the api defined in [wintun.h](https://github.com/WireGuard/wintun/blob/master/api/wintun.h).
Here is a copy of the [license](https://gist.github.com/ofer-dev/6ef9c46c5a6c03bf17cba206123e81ba).

**Comment by wadey** [comment]
It looks like @ofer-dev is correct, and the .dll is distributed with a permissible license, one that we could bundle with an installer for Windows and not be concerned about licensing issues. The license is viewable in the wintun repo here: https://github.com/WireGuard/wintun/blob/master/prebuilt-binaries-license.txt

@CzBiX Would you like to take the effort of upgrading this PR for Wintun 0.10, or would you like to hand it over and we can work on it? Thanks again for your effort so far!

**Comment by wadey** [comment]
Also, if you decide to update this PR, don't worry about how to bundle the .dll for distribution. We will work on a different PR to build an installer with the DLL during the release process.

**Comment by CzBiX** [comment]
Since we will bundle the dll, I think we can remove `water tun` implementation now.

**Comment by CzBiX** [comment]
@jamescorbett put the right `wintun.dll` into same folder with `nebula.exe`, then run nebula with administrator privileges.

**Comment by gustavokei** [comment]
This seems to solve [#9](https://github.com/slackhq/nebula/issues/9#issuecomment-761974328) on Windows 10. I had the same problem.
It is also a much better solution than installing the entire OpenVPN package.

Got it working by building @CzBiX [fork](https://github.com/CzBiX/nebula/tree/wintun) and putting the `wintun.dll` into the same folder with `nebula.exe`
Hopefully this gets merged soon!

Awesome project, really appreciate your work!

**Comment by paz** [comment]
any updates on this?

**Comment by tskarman** [comment]
Just wanted to let you know that the CzBiX fork still appears to work well with the current Wintun version 0.13 (https://www.wintun.net/builds/wintun-0.13.zip)

Transfer speed on Windows is still markedly behind WireGuard in my situation but still ahead of the Nebula 1.4 Open-VPN-TAP-based version. But there's no point discussing that before there is a stable release.

**Review by wadey — APPROVED** [review]
I haven't been able to test this myself as I don't have a Windows system running currently, but the code looks good and I trust that it is running and working properly.

**Pull request merged**
