### PR TITLE
fix winwin branch from nbrownus to work with relay update

### PR DESCRIPTION
**Pull request by OvrAp3x**
the winwin branch from @nbrownus improves windows performance significantly, practically unusable before this. 
This PR contains his code + a small fix to make it work with the current code base.

### CODE REVIEW

**Comment by CoREse** [comment]
Thank you, I used your version and it really improved the performance. Hope this PR is going to be accepted sooner.

**Comment by DavidMSCode** [comment]
I can also confirm this fixes performance on windows. I was seeing ~4/300 Mbps down/up on a gigabit network with my win11 box using Firefox to connect to my local Ubuntu install running Open Speed Test. With this PR I'm seeing ~800/600 Mbps which is what I get using the local IP rather than the overlay IP.

**Comment by QZAiXH** [comment]
This PR does work, so why hasn't it been merged into master for so long?

**Comment by SamSirry** [comment]
Perhaps they're waiting for @OvrAp3x to sign the agreement.

**Comment by OvrAp3x** [comment]
I have done so, 
Just waiting for nebula team

**Comment by QZAiXH** [comment]
This pr does improve the speed on Windows, so why hasn't it been merged into master until now? @nbrownus

**Comment by nbrownus** [comment]
This was merged in #905

**Pull request closed without merging**
