### PR TITLE
dns: Handle DNS short failures at startup

### PR DESCRIPTION
**Pull request by ton31337**
Not the first time we got DNS resolver error and Nebula failed to start.

Let's handle this a bit more gracefuly.

Signed-off-by: Donatas Abraitis <donatas.abraitis@gmail.com>

### CODE REVIEW

**Comment by ton31337** [comment]
@nbrownus @wadey could you take a look here? If not, it can be closed.

**Comment by JohnMaguire** [comment]
@ton31337 Are you using a systemd init script to start Nebula? I'm curious if you have an `After=network-online.target` line in your file?

**Comment by ton31337** [comment]
> @ton31337 Are you using a systemd init script to start Nebula? I'm curious if you have an `After=network-online.target` line in your file?

Of course.

**Comment by ton31337** [comment]
ping

**Pull request closed without merging**
